---
dataset_path: "data/versioned_data/replica_cad_baked_lighting_1.1/replicaCAD_baked.scene_dataset_config.json"
additional_object_paths:
  - "data/objects/ycb/"
scene_sets:
  -
    name: "v3_sc"
    included_substrings:
      - "v3_sc"
    excluded_substrings: ["Baked_sc1_staging_00_bench"]
    comment: "This set (v3_sc) selects all 105 ReplicaCAD variations with static furniture."
  -
    name: "v3_sc1_staging_00_bench"
    included_substrings:
      - "Baked_sc1_staging_00_bench"
    excluded_substrings: []
    comment: "Benchmarking test scene"

object_sets:
  -
    name: "any"
    included_substrings:
      - ""
    excluded_substrings: []
    comment: "The empty substring acts like a wildcard, selecting all objects."
  -
    name: "kitchen"
    included_substrings:
      - "002_master_chef_can"
      - "003_cracker_box"
      - "004_sugar_box"
      - "005_tomato_soup_can"
      - "007_tuna_fish_can"
      - "008_pudding_box"
      - "009_gelatin_box"
      - "010_potted_meat_can"
      - "024_bowl"
    excluded_substrings: []

receptacle_sets:
  -
    name: "table"
    included_object_substrings:
      - "frl_apartment_table_01"
    excluded_object_substrings: []
    included_receptacle_substrings:
      - ""
    excluded_receptacle_substrings: []
    comment: "The empty substrings act like wildcards, selecting all receptacles for all objects."
  -
    name: "fridge"
    included_object_substrings:
      - "fridge"
    excluded_object_substrings: []
    included_receptacle_substrings:
      - ""
    excluded_receptacle_substrings: []
  -
    name: "counter"
    included_object_substrings:
      - "kitchen_counter"
    excluded_object_substrings: []
    included_receptacle_substrings:
      - ""
    excluded_receptacle_substrings: []

scene_sampler:
  type: "subset"
  params:
    scene_sets: ["v3_sc1_staging_00_bench"]
  comment: "Samples from ReplicaCAD 105 variations with static furniture."

ao_state_samplers:
  -
    name: "open_aos"
    type: "composite"
    params:
      -
        ao_handle: "fridge"
        joint_states:
          - ["top_door", 1.5, 1.5]
      -
        ao_handle: "counter"
        joint_states:
          - ["drawer1_top", 0.25, 0.25]
          - ["drawer1_bottom", 0.5, 0.5]
          - ["drawer2_top", 0.5, 0.5]
          - ["drawer2_middle", 0.35, 0.35]
          - ["drawer2_bottom", 0.5, 0.5]
          - ["drawer3", 0.25, 0.25]
          - ["drawer4", 0.5, 0.5]
    comment: "For composite samplers, one param entry per AO and one joint state entry per joint: (name, min, max)."

object_samplers:
  -
    name: "kitchen_counter"
    type: "uniform"
    params:
      object_sets: ["kitchen"]
      receptacle_sets: ["counter"]
      num_samples: [8, 8]
      orientation_sampling: "up"
  -
    name: "kitchen_fridge"
    type: "uniform"
    params:
      object_sets: ["kitchen"]
      receptacle_sets: ["fridge"]
      num_samples: [7, 7]
      orientation_sampling: "up"
